// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeklLjfnwbs0lzvublxL8Jvs9hYbqSQaE',
    appId: '1:113636929999:web:38e561666d4adc4591e2ba',
    messagingSenderId: '113636929999',
    projectId: 'sharkchat-7d8b2',
    authDomain: 'sharkchat-7d8b2.firebaseapp.com',
    storageBucket: 'sharkchat-7d8b2.appspot.com',
    measurementId: 'G-GWYS483C0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5eqly4-PT6OUvTP0Xyxi4LwZUkFT9XY',
    appId: '1:113636929999:android:65814f7b1fa1e0dd91e2ba',
    messagingSenderId: '113636929999',
    projectId: 'sharkchat-7d8b2',
    storageBucket: 'sharkchat-7d8b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4nmZIy2sdGK1qDpBAIsdVCx09SN3Yos',
    appId: '1:113636929999:ios:2bd61eaa1bfb96b991e2ba',
    messagingSenderId: '113636929999',
    projectId: 'sharkchat-7d8b2',
    storageBucket: 'sharkchat-7d8b2.appspot.com',
    iosClientId: '113636929999-jjiafl7grfdp37funorgp4c1spch7s3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.shark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4nmZIy2sdGK1qDpBAIsdVCx09SN3Yos',
    appId: '1:113636929999:ios:2bd61eaa1bfb96b991e2ba',
    messagingSenderId: '113636929999',
    projectId: 'sharkchat-7d8b2',
    storageBucket: 'sharkchat-7d8b2.appspot.com',
    iosClientId: '113636929999-jjiafl7grfdp37funorgp4c1spch7s3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.shark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeklLjfnwbs0lzvublxL8Jvs9hYbqSQaE',
    appId: '1:113636929999:web:dd87a6be624acbbe91e2ba',
    messagingSenderId: '113636929999',
    projectId: 'sharkchat-7d8b2',
    authDomain: 'sharkchat-7d8b2.firebaseapp.com',
    storageBucket: 'sharkchat-7d8b2.appspot.com',
    measurementId: 'G-WXX4FJ2PPE',
  );
}
